name: ItemRemapper
version: ${project.version}
main: com.itemremapper.ItemRemapperPlugin
api-version: '1.21'
author: Immuc
description: Automatically remaps item names when they enter player inventories and customizes jukebox messages
softdepend: [ProtocolLib]
commands:
  itemremapper:
    description: ItemRemapper management commands
    usage: /itemremapper <reload>
    aliases: [ir, remapper]
    permission: itemremapper.admin
